openapi: 3.0.0
info:
  title: PecoNote API
  version: 1.0.0
paths:
  /api/memos:
    get:
      summary: List memos
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 1
            default: 1
        - in: query
          name: page_size
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - in: query
          name: tag
          schema:
            type: string
            maxLength: 30
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoListResponse'
    post:
      summary: Create memo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MemoCreateRequest'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MemoCreateResponse'
components:
  schemas:
    MemoCreateRequest:
      type: object
      properties:
        body:
          type: string
        tags:
          type: array
          items:
            type: string
      required: [body]
    MemoCreateResponse:
      type: object
      properties:
        id:
          type: string
    MemoItem:
      type: object
      properties:
        id:
          type: string
        body:
          type: string
        tags:
          type: array
          items:
            type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Pagination:
      type: object
      properties:
        page:
          type: integer
        page_size:
          type: integer
        total_pages:
          type: integer
        total_count:
          type: integer
    MemoListResponse:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/MemoItem'
        pagination:
          $ref: '#/components/schemas/Pagination'
